import { SlackAPI, SlackEntity } from 'app/types/slack/';
import { toObject } from 'app/features/slack/module';

export const rowChannels = ({
  ok: true,
  channels: [
    {
      id: 'channels_id',
      name: 'times_simenyan',
      is_channel: true,
      is_im: false,
      created: 1431338621,
      is_archived: false,
      is_general: false,
      unlinked: 0,
      creator: 'channels_creator_id',
      name_normalized: 'times_simenyan',
      is_shared: false,
      is_org_shared: false,
      is_member: true,
      is_private: false,
      is_mpim: false,
      members: ['member_id'],
      topic: {
        value: 'とぴっく',
        creator: 'topic_creator_id',
        last_set: 1494373387,
      },
      purpose: {
        value:
          "A place for non-work-related flimflam, faffing, hodge-podge or jibber-jabber you'd prefer to keep out of more focused work-related channels.",
        creator: '',
        last_set: 0,
      },
      previous_names: ['random'],
      num_members: 449,
    },
    {
      id: 'archived_channel_id',
      name: 'archived_channel',
      is_channel: true,
      is_im: false,
      created: 1432271741,
      is_archived: true,
      is_general: false,
      unlinked: 0,
      creator: 'archived_channel_user',
      name_normalized: 'archived_channel',
      is_shared: false,
      is_org_shared: false,
      is_member: false,
      is_private: false,
      is_mpim: false,
      members: [],
      topic: {
        value: 'archived_channel_topic',
        creator: 'archived_channel_topic_creator',
        last_set: 1435063806,
      },
      purpose: {
        value: 'archived_channel_purpose',
        creator: 'archived_channel_purpose_creator',
        last_set: 1432271742,
      },
      previous_names: [],
      num_members: 0,
    },
    {
      id: 'times_simenyan_id',
      name: 'times_simenyan',
      is_channel: true,
      is_im: false,
      created: 1465522596,
      is_archived: false,
      is_general: false,
      unlinked: 0,
      creator: 'times_simenyan_creator_id',
      name_normalized: 'times_simenyan',
      is_shared: false,
      is_org_shared: false,
      is_member: true,
      is_private: false,
      is_mpim: false,
      members: ['times_simenyan_member'],
      topic: {
        value: 'topic_value',
        creator: 'times_simenyan_topic_creator_id',
        last_set: 1541080889,
      },
      purpose: {
        value: 'しめにゃんのつぶやき部屋',
        creator: 'times_simenyan_purpose_creator_id',
        last_set: 1468210326,
      },
      previous_names: ['times_sisisin'],
      num_members: 39,
    },
  ],
  response_metadata: {
    next_cursor: '',
  },
} as unknown) as SlackAPI.Conversations.List;

export const channels = toObject<SlackEntity.Conversation>(rowChannels.channels);
