import { toObject } from 'app/features/slack/module';

export const rowUsers = {
  ok: true,
  members: [
    {
      id: 'user_id_1',
      team_id: 'team_id_1',
      name: 'slackbot',
      deleted: false,
      color: '757575',
      real_name: 'slackbot',
      tz: null,
      tz_label: 'Pacific Standard Time',
      tz_offset: -28800,
      profile: {
        title: '',
        phone: '',
        skype: '',
        real_name: 'slackbot',
        real_name_normalized: 'slackbot',
        display_name: 'slackbot',
        display_name_normalized: 'slackbot',
        fields: null,
        status_text: '',
        status_emoji: '',
        status_expiration: 0,
        avatar_hash: 'sv1444671949',
        always_active: true,
        first_name: 'slackbot',
        last_name: '',
        image_24: 'https://a.slack-edge.com/0180/img/slackbot_24.png',
        image_32: 'https://a.slack-edge.com/7f1a0/plugins/slackbot/assets/service_32.png',
        image_48: 'https://a.slack-edge.com/7f1a0/plugins/slackbot/assets/service_48.png',
        image_72: 'https://a.slack-edge.com/0180/img/slackbot_72.png',
        image_192: 'https://a.slack-edge.com/66f9/img/slackbot_192.png',
        image_512: 'https://a.slack-edge.com/1801/img/slackbot_512.png',
        status_text_canonical: '',
        team: 'T04Q5G460',
      },
      is_admin: false,
      is_owner: false,
      is_primary_owner: false,
      is_restricted: false,
      is_ultra_restricted: false,
      is_bot: false,
      is_app_user: false,
      updated: 0,
    },
    {
      id: 'admin_user_id',
      team_id: 'team_id_1',
      name: 'admin_user',
      deleted: false,
      color: '9f69e7',
      real_name: 'Admin User',
      tz: 'Asia/Tokyo',
      tz_label: 'Japan Standard Time',
      tz_offset: 32400,
      profile: {
        title: 'admin_user title',
        phone: '',
        skype: '',
        real_name: 'Admin User',
        real_name_normalized: 'Admin User',
        display_name: 'admin_user',
        display_name_normalized: 'admin_user',
        status_text: 'admin_user status text',
        status_emoji: ':innocent:',
        status_expiration: 0,
        avatar_hash: 'hash_value',
        email: 'admin_user@example.com',
        first_name: 'Admin',
        last_name: 'User',
        image_24: '/assets/storybook/user_1.jpg',
        image_32: '/assets/storybook/user_1.jpg',
        image_48: '/assets/storybook/user_1.jpg',
        image_72: '/assets/storybook/user_1.jpg',
        image_192: '/assets/storybook/user_1.jpg',
        image_512: '/assets/storybook/user_1.jpg',
        status_text_canonical: '',
        team: 'T04Q5G460',
      },
      is_admin: true,
      is_owner: true,
      is_primary_owner: true,
      is_restricted: false,
      is_ultra_restricted: false,
      is_bot: false,
      is_app_user: false,
      updated: 1542619490,
      has_2fa: true,
      two_factor_type: 'app',
    },
  ],
  cache_ts: 1542619499,
  response_metadata: {
    next_cursor: '',
  },
};

export const users = toObject(rowUsers.members);
