apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 1163fe4b-9ebb-405c-8fe1-80d33ced25b7
  labels:
    cloud.googleapis.com/location: us-central1
  name: chattun-server
  namespace: '31671566034'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: sisisin/chattun-server:20231017-000025
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: SERVER_BASE_URL
          value: https://chattun-server-abfreslzha-uc.a.run.app
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: '1'
              name: redis-url
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              key: '1'
              name: slack-app-token
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: '1'
              name: slack-client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: '1'
              name: slack-client-secret
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: chattun-server-run@knowledgework-simenyan-sandbox.iam.gserviceaccount.com
      timeoutSeconds: 3600
  traffic:
  - latestRevision: true
    percent: 100
