#!/usr/bin/env bash

set -ef -o pipefail

readonly work_dir=$(cd "$(dirname "$0")" && pwd)
cd $work_dir

if [ $# -ne 1 ]; then
    echo "Usage: $0 <project_id>"
    exit 1
fi

readonly project_id=$1

gcloud run services replace ../service.yaml --project "$project_id"
