name: Notify deploy workflow completed
on:
  workflow_run:
    workflows: ['Build and deploy to Cloud Run']
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Notify deploy completed details to slack
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await require('./.github/scripts/notify.js')({github,context})
