name: Notify deploy workflow completed
on:
  workflow_run:
    workflows: ['Build and deploy to Cloud Run']
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify deploy completed details to slack
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const discordWebhookUrl = process.env.DISCORD_WEBHOOK_URL;
            if (!discordWebhookUrl) {
              throw new Error('DISCORD_WEBHOOK_URL is not set');
            }
            const { data } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
              per_page: 100,
            });

            const hasFailed = data.jobs.some((j) => j.conclusion === 'failure');
            const response = await fetch(discordWebhookUrl, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                content: `chattun deploy ${hasFailed ? 'failure' : 'success'}`,
                username: 'chattun bot',
              }),
            });
            if (!response.ok) {
              throw new Error(`Failed to send notification: ${response.statusText}`);
            }
            core.info('Notification sent successfully');
